---
#
# Project:: Ansible Role - CHANGEME
#
# Copyright 2022, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# CHANGEME ROLE DESCRIPTION

- import_tasks: prereqs.yml
  when: ansible_distribution == 'Ubuntu'
